#!/bin/bash

for dotfile in `ls -a | grep "^\.[a-z]" | cut -d\/ -f1 | grep -v "^\.git$" | grep -v "^\.gitignore$"`;
do
    ln -s -i $PWD/$dotfile ~
done

# vim
ln -s -i $PWD/vim/colors ~/.vim/colors

